---
title: "Prospective analysis with typing delay"
---

```{r include=FALSE}
source("ranScanInit2.r")
case.file = "Data/Full MOLIS dataset minus PII 20200918.xlsx"
case.df = ranScanInit(case.file)
```


```{r}
emmtype='44.0' ##44.0 #1.0 #33.0
n.weeks = 150
starting.week = 80
case.df$`Patient Postcode` %>% unique %>% head(14)
```

```{r}
ranScanCreateObservationMatrices.delay(case.file, emmtype, starting.week = starting.week, n.weeks = n.weeks)
```


```{r}
load(sprintf("Data/%s_typed_obs.Rdata", emmtype), verbose = 1)
load('Data/untyped_obs.Rdata', verbose = 1)

print(head(names(observation.matrices.untyped)))
observation.matrices.untyped[['150']][1:5,1:5]
observation.matrices.untyped[[10]] %>% rownames %>% head
observation.matrices.typed[[emmtype]][['150']][1:5,1:5]
case.df$`Patient Postcode` %>% unique %>% head(14)

```


```{r}
init=Sys.time()
postcode2coord = ranScanPostcodeMap(observation.matrices.untyped[[1]])
print(Sys.time()-init)
```

```{r}
time.factor = ranScanTimeFactor(case.file)
```

```{r}
baseline.matrix = ranScanCreateBaselineMatrix(case.file)
```

```{r}
emmtype.factor = ranScanEmmtypeFactor.tau(case.file, emmtype)
delay.factor = ranScanEmmtypeFactor.delay_(case.file, starting.week = starting.week, n.weeks = n.weeks)
```

```{r}
for (t in as.character(seq(150,290, 15))){
  cols = colnames(observation.matrices.untyped[[t]])
  emt.factor = emmtype.factor[[emmtype]][cols]
  dly.factor = delay.factor
  
  bsl.matrix.typed = baseline.matrix[,cols] * rep((1 - dly.factor) * emt.factor,
                                                      rep(NROW(baseline.matrix[,cols]),
                                                          NCOL(baseline.matrix[,cols])))
  
  bsl.matrix.untyped = baseline.matrix[,cols] * rep(dly.factor,
                                                      rep(NROW(baseline.matrix[,cols]),
                                                          NCOL(baseline.matrix[,cols])))
  x = as.integer(colnames(observation.matrices.typed[[emmtype]][[t]]))
  y = colSums(observation.matrices.typed[[emmtype]][[t]])
  y1 = colSums(observation.matrices.untyped[[t]])
  plot(range(x), c(0, max(c(y,y1))), xlab = bquote(tau~'[week]'), ylab='no. cases per week', col=NA,
       main=sprintf('screenshot at week %s', t))
  y = ifelse(y > 0, y, NA)
  y1 = ifelse(y1 > 0, y1, NA)
  points(x, y, col='red', pch=20)
  points(x, y1)
  idx = !(rownames(bsl.matrix.typed) == 'NA')
  lines(x, colSums(bsl.matrix.typed[idx,]), col='red')
  lines(x, colSums(bsl.matrix.untyped[idx,]))
  legend('topleft', legend=c(sprintf('emm %s observations', emmtype), 'untyped observations', sprintf('emm %s baseline',emmtype), 'untyped baseline'), pch=c(20, 1, NA, NA), col=c('red','black','red','black'), lty = c(NA,NA,1,1))
  
  cat(t, "total bsl", sum(bsl.matrix.typed, na.rm = T) + sum(bsl.matrix.untyped, na.rm = T), '\n')
  cat(t, "total observed cases", sum(y, na.rm = T) + sum( y1, na.rm = T), '\n')
}
```

```{r}
png(paste0('Fig/baseline_vs_delay',label.str,'.png'), width = 4 * 1.2, height = 3 * 1.2, units = 'in', res=600, pointsize = 11)
par(mfrow=c(1,1), mar=c(4,4,1,1))
cols = colnames(observation.matrices.untyped[[t]])
emt.factor = emmtype.factor[[emmtype]][cols]
dly.factor = delay.factor
bsl.matrix.typed = baseline.matrix[,cols] * rep((1 - dly.factor) * emt.factor,
                                                rep(NROW(baseline.matrix[,cols]),
                                                NCOL(baseline.matrix[,cols])))
#
bsl.matrix.untyped = baseline.matrix[,cols] * rep(dly.factor,
                                                  rep(NROW(baseline.matrix[,cols]),
                                                  NCOL(baseline.matrix[,cols])))
#
x = as.integer(colnames(observation.matrices.typed[[emmtype]][[t]]))
y = colSums(observation.matrices.typed[[emmtype]][[t]])
y1 = colSums(observation.matrices.untyped[[t]])
plot(range(x), c(0, max(c(y,y1))), xlab = "observation date", ylab='no. cases per week', col=NA, #
     main=sprintf('snapshot on %s', week2Date(t)), xaxt='n', xlim=c(max(x)-90,max(x)))
y = ifelse(y > 0, y, NA)
y1 = ifelse(y1 > 0, y1, NA)
points(x, y, col='#d62728', pch=20)
points(x, y1, col='#7f7f7f')
by=1
axis(1, at=seq(max(x),1, by=-by), labels=NA)
by=20
axis(1, at=seq(max(x),1, by=-by), labels=week2Date(seq(max(x),1, by=-by)), tck=-0.05)

#axis(1, seq(0.5, 9.5, 1), labels=rep("", 10), tck=-0.01)

idx = !(rownames(bsl.matrix.typed) == 'NA')
lines(x, colSums(bsl.matrix.typed[idx,]), col='#d62728')
lines(x, colSums(bsl.matrix.untyped[idx,]), col='#7f7f7f', lty='dotdash')
legend('topleft', legend=c(sprintf('emm %s observations', emmtype), 'untyped observations', sprintf('emm %s baseline',emmtype), 'untyped baseline'), pch=c(20, 1, NA, NA), col=c('#d62728','#7f7f7f','#d62728','#7f7f7f'), lty = c(NA,NA,1,4))
dev.off()
```


# model for delay
```{r}
L=len(dly.factor)
y = dly.factor[(L-10):L]
geo<-function(r){r**(10:0)}
rmsd = function(x,y){  return( sqrt( mean((x-y)**2))) }
rest = optimize(function(x){  rmsd(geo(x), y)}, c(0, 1) )$minimum
plot(-10:0, y, ylab = 'Fraction of untyped cases', xlab = 'time elapsed from detection date [week]', xaxt='n', col='#1f77b4', xlim = c(-6,0))
axis(1, at = -10:0, labels=-(-10:0))
#lines(10:0, geo(rest))
leng=100
rest_ = vector(mode = "numeric", length = leng)
for (i in 1:leng){
   idx = sample(1:11, replace = T)
   rest_[i] = optimize(function(x){  rmsd(  geo(x)[idx],  y[idx])}, c(0, 1) )$minimum
}
#rest_ = quantile(rest_, c(0.025, 0.5,0.975))
rest_ = quantile(rest_, c(0.158, 0.5,0.6827+0.158))
print(rest_)
#lines(-10:0, geo(rest_[1]), col='#1f77b4')
points(-10:0, geo(rest_[2]), col='#ff7f0e', pch=19)
lines(-10:0, geo(rest_[2]), col='#ff7f0e', lty=2)
#lines(-10:0, geo(rest_[3]), col='red')
ylow=geo(rest_[1])
yupp=geo(rest_[3])
x = -10:0
for (i in 1:length(x)){
  segments(x0 =x[i], y0 = ylow[i], x1 = x[i], y1 = yupp[i], col='#ff7f0e' )
  print(c(x[i], yupp[i]))
}
points(-10:0, y, ylab = 'Fraction of untyped cases', xlab = 'time elapsed from detection date [week]', xaxt='n', col='#1f77b4', xlim = c(-6,0))
legend('topleft',legend = c('data', 'fit'), col = c('#1f77b4','#ff7f0e'), lty = c(NA, 2), pch=c(1,19))
```


```{r}
# tab:blue : #1f77b4
# tab:orange : #ff7f0e
# tab:green : #2ca02c
# tab:red : #d62728
# tab:purple : #9467bd
# tab:brown : #8c564b
# tab:pink : #e377c2
# tab:gray : #7f7f7f
# tab:olive : #bcbd22
# tab:cyan : #17becf
```

```{r include=FALSE}
source("ranScanEvaluate.r")
```

```{r include=FALSE}
sizefactor = 1.2
n_cyl = 50000 # min(50000, sum(obs.matrix.typed[-13,]) * 10 )
weeks = attributes(observation.matrices.untyped)$names
n.rows = sum(case.df$emmtype == emmtype)
n.cols = length(weeks)

to.export.strategy1 = as.data.frame(matrix(NA, nrow = n.rows, ncol = n.cols))
to.export.strategy2 = as.data.frame(matrix(NA, nrow = n.rows, ncol = n.cols))
names(to.export.strategy1) = mapply(function(x){week2Date(x)}, as.character(weeks))
names(to.export.strategy2) = mapply(function(x){week2Date(x)}, as.character(weeks))

dly.factor = delay.factor
  
for (week in weeks){
  writeLines(week)
  
  cols = colnames(observation.matrices.untyped[[week]])
  emt.factor = emmtype.factor[[emmtype]][cols]
  
  obs.matrix.typed = observation.matrices.typed[[emmtype]][[week]]
  obs.matrix.untyped = observation.matrices.untyped[[week]] * rep(emt.factor,
                                                                  rep(NROW(observation.matrices.untyped[[week]]),
                                                                      NCOL(observation.matrices.untyped[[week]])))
  obs.matrix = obs.matrix.typed + obs.matrix.untyped

  bsl.matrix.typed = baseline.matrix[,cols] * rep((1 - dly.factor) * emt.factor,
                                                  rep(NROW(baseline.matrix[,cols]),
                                                      NCOL(baseline.matrix[,cols])))
  bsl.matrix.untyped = baseline.matrix[,cols] * rep(dly.factor * emt.factor,
                                                     rep(NROW(baseline.matrix[,cols]),
                                                         NCOL(baseline.matrix[,cols])))
  bsl.matrix = bsl.matrix.typed + bsl.matrix.untyped
  
  week.range = range(as.integer(cols))
  cylinders.strategy1 = ranScanCreateCylinders.delay(obs.matrix.typed, bsl.matrix.typed,
                                           obs.matrix.untyped, bsl.matrix.untyped,
                                           emmtype, week.range,
                                           n_cyl, postcode2coord, size_factor = sizefactor)
  cylinders.strategy2 = ranScanCreateCylinders(obs.matrix, bsl.matrix,
                                     emmtype, week.range,
                                     n_cyl, postcode2coord, size_factor = sizefactor)
  case.df.tmp = ranScanEvaluate(case.file, cylinders.strategy1, emmtype, p.val.threshold=0.05)
  ws = case.df.tmp[case.df.tmp$emmtype == emmtype,]$warning.score
  i = as.integer(week) - as.integer(weeks[1]) + 1
  to.export.strategy1[, i] = ws
  
  case.df.tmp = ranScanEvaluate(case.file, cylinders.strategy2, emmtype, p.val.threshold=0.05)
  ws = case.df.tmp[case.df.tmp$emmtype == emmtype,]$warning.score
  i = as.integer(week) - as.integer(weeks[1]) + 1
  to.export.strategy2[, i] = ws
}
```

```{r}
dataframe.to.export = cbind(case.df.tmp[case.df.tmp$emmtype == emmtype,], to.export.strategy1)
dataframe.to.export$warning.score = NULL
write.csv(dataframe.to.export, file = paste0('emmtype_', emmtype, '__strategy1_delay.csv'))

dataframe.to.export = cbind(case.df.tmp[case.df.tmp$emmtype == emmtype,], to.export.strategy2)
dataframe.to.export$warning.score = NULL
write.csv(dataframe.to.export, file = paste0('emmtype_', emmtype, '__strategy2_delay.csv'))
rm(dataframe.to.export)
```


```{r}
strategy1_delay = read.csv(paste0('emmtype_', emmtype, '___strategy1_delay.csv'),
                                         row.names = 1, check.names = F)
plot.spaghetti(strategy1_delay)
strategy2_delay = read.csv(paste0('emmtype_', emmtype, '___strategy2_delay.csv'),
                                         row.names = 1, check.names = F)
plot.spaghetti(strategy2_delay)
```


```{r}
plot.strategy.compare(115, strategy1_delay, strategy2_delay,
                      tab.orange, tab.blue, "strategy 1", "strategy 2", xlim=c(50,142))
```



```{r}
no.delay = read.csv(paste0('emmtype_', emmtype, '___no_delay_receipt.csv'), row.names = 1, check.names = F)
plot.strategy.compare(115, strategy1_delay, no.delay,
                      tab.orange, tab.blue, "with delay", "naive", xlim=c(50,142))


```

```{r}
plot.strategy.compare(500, strategy1_delay, no.delay,
                      tab.orange, tab.blue, "with delay", "naive", xlim=c(50,110), ylim=c(0.6,1)) #h191320275, h191440186,h191480689
```

```{r}
plot.strategy.compare(4, strategy2_delay, no.delay,
                      tab.orange, tab.blue, "with delay", "naive", xlim=c(1,142), threshold = 0, first.row = 64)
```


# figure

```{r}
png(paste0('Fig/strategy_comparison.png'), width = 4 * 1.2, height = 3 * 1.2, units = 'in', res=600, pointsize = 11)
par(mfrow=c(1,1), mar=c(4,4,1,1))
s1 = strategy1_delay[which(strategy1_delay$FULLNO=='H191320275'),]
s2 = strategy2_delay[which(strategy2_delay$FULLNO=='H191320275'),]
s3 = no.delay[which(no.delay$FULLNO=='H191320275'),]
x = intersect(intersect(colnames(s1), colnames(s2)), colnames(s3))
x = x[-(1:16)]
plot(c(1,length(x)), range(c(s1[x],s2[x],s3[x])),
     xlab='', ylab='w', type = 'n', xlim=c(71,80)-1, ylim=c(0.4,1), xaxt='n',  cex=0.6)
cat(sprintf("Sampled on %s - typed on %s", week2Date(s1$SAMPLE_DT_numeric), week2Date(s1$RECEPT_DT_numeric) ))
abline(h=0.95, col=tab.gray)
axis(side = 1, at = seq(1,length(x),2), labels = x[seq(1,length(x),2)], cex.axis=0.8, las=1, tck=-0.07)
axis(side = 1, at = seq(2,length(x),2), labels = x[seq(2,length(x),2)], cex.axis=0.8, las=1,  padj=-1.5)

idx = s1[x] > 0
lines((1:length(x))[idx],s1[x][idx], col=tab.blue, lty=1)
points((1:length(x))[idx],s1[x][idx], col=tab.blue, pch=1)
idx = s2[x] > 0
lines((1:length(x))[idx],s2[x][idx], col=tab.orange, lty=2)
points((1:length(x))[idx],s2[x][idx], col=tab.orange, pch=2)
idx = s3[x] > 0
lines((1:length(x))[idx],s3[x][idx], col=tab.green, lty=3)
points((1:length(x))[idx],s3[x][idx], col=tab.green, pch=3)
legend("bottomright", c("Strategy 1", "Strategy 2", "Naive"),
       lty=c(1,2,3), pch=c(1,2,3), col=c(tab.blue, tab.orange, tab.green))
dev.off()

png(paste0('Fig/strategy_comparison_2.png'), width = 4 * 1.2, height = 3 * 1.2, units = 'in', res=600, pointsize = 11)
par(mfrow=c(1,1), mar=c(4,4,1,1))
s1 = strategy1_delay[which(strategy1_delay$FULLNO=='H191480689'),]
s2 = strategy2_delay[which(strategy2_delay$FULLNO=='H191480689'),]
s3 = no.delay[which(no.delay$FULLNO=='H191480689'),]
x = intersect(intersect(colnames(s1), colnames(s2)), colnames(s3))
x = x[-(1:16)]
plot(c(1,length(x)), range(c(s1[x],s2[x],s3[x])),
     xlab='', ylab='w', type = 'n', xlim=c(71,80), ylim=c(0.6,1), xaxt='n',  cex=0.6)
cat(sprintf("Sampled on %s - typed on %s", week2Date(s1$SAMPLE_DT_numeric), week2Date(s1$RECEPT_DT_numeric) ))
abline(h=0.95, col=tab.gray)
axis(side = 1, at = seq(1,length(x),2), labels = x[seq(1,length(x),2)], cex.axis=0.8, las=1, tck=-0.07)
axis(side = 1, at = seq(2,length(x),2), labels = x[seq(2,length(x),2)], cex.axis=0.8, las=1,  padj=-1.5)

idx = s1[x] > 0
lines((1:length(x))[idx],s1[x][idx], col=tab.blue, lty=1)
points((1:length(x))[idx],s1[x][idx], col=tab.blue, pch=1)
idx = s2[x] > 0
lines((1:length(x))[idx],s2[x][idx], col=tab.orange, lty=2)
points((1:length(x))[idx],s2[x][idx], col=tab.orange, pch=2)
idx = s3[x] > 0
lines((1:length(x))[idx],s3[x][idx], col=tab.green, lty=3)
points((1:length(x))[idx],s3[x][idx], col=tab.green, pch=3)
legend("bottomright", c("Strategy 1", "Strategy 2", "Naive"),
       lty=c(1,2,3), pch=c(1,2,3), col=c(tab.blue, tab.orange, tab.green))
dev.off()
```



# comparison delay vs no-delay

```{r}
no_delay = read.csv(paste0('emmtype_', emmtype, '__no_delay.csv'), row.names = 1, check.names = F)

# rownames(emmtype_44_0_sf1_2) = emmtype_44_0_sf1_2$X
# rownames(dataframe.to.export)= dataframe.to.export$X
tmp = no_delay[rownames(strategy2_delay),]
idx = which(tmp[, 219] > 0.95)
# 
# weeks = 150:293
# for (i in 10:2300){
#   if( !is.na(tmp[i,'x']) & i %in%  idx){
#     title = sprintf("sampled %d - typed on %d", tmp[i,'SAMPLE_DT_numeric'], tmp[i,'RECEPT_DT_numeric'] )
#     plot(c(150,293), c(0,1), col='white', xlab = 'week', ylab='warning score', main=title)
#     lines(150:293,
#           unlist(dataframe.to.export[i, 17:160]), xlab = 'week', ylab='warning score', col=tab.orange)
#     lines(96:298,
#           unlist(tmp[i,17:219]), col=tab.blue)
#     abline(h = 0.95, col = tab.gray)
#     legend("topleft", legend = c("with delay","naive"), col = c(tab.orange,tab.blue), lty = c(1,1))
#   }
# }
```



```{r}
dataframe.to.export = read.csv(file = paste0('emmtype_', emmtype, '__strategy2_delay.csv'))
emmtype_44_0_sf1_2 <- read.csv("emmtype_44.0_sf1.2.csv")
rownames(emmtype_44_0_sf1_2) = emmtype_44_0_sf1_2$X
rownames(dataframe.to.export)= dataframe.to.export$X
tmp = emmtype_44_0_sf1_2[rownames(dataframe.to.export),]
idx = which(tmp[, 219] > 0.95)

weeks = 150:293
for (i in 10:2300){
  if( !is.na(tmp[i,'x']) & i %in%  idx){
    title = sprintf("sampled %d - typed on %d", tmp[i,'SAMPLE_DT_numeric'], tmp[i,'RECEPT_DT_numeric'] )
    plot(c(150,293), c(0,1), col='white', xlab = 'week', ylab='warning score', main=title)
    
    lines(150:293, unlist(dataframe.to.export[i, 17:160]), xlab = 'week', ylab='warning score', col=tab.orange)
    lines(96:298, unlist(tmp[i, 17:219]), col=tab.blue)
    
    abline(h=0.95, col=tab.gray)
    legend("topleft", legend = c("with delay","naive"), col=c(tab.orange,tab.blue), lty=c(1,1))
  }
}
```





```{r}
```
