---
title: "Surveillance 3D"
author: "Massimo Cavallaro"
date: "22 October 2019"
output:
  pdf_document: default
  word_document: default
---

```{r}
library(spatstat)

spatial.trend.function<-function(x,y, C=80, B=0.5, x0=0.5, y0=0.5){
  # return(1000*(B + 20*exp(-C * ( (x-x0)^2 + (y - y0)^2))))
  return(rep(1285.398, len(x)))
}
```

```{r}
set.seed(1)
A = rpoispp(function(x,y){spatial.trend.function(x,y)})
```

```{r}
observations = data.frame(x=A$x, y=A$y)
x = rep(seq(0,1,length.out = 100), 100)
y = rep(seq(0,1,length.out = 100), rep(100,100))
#
tabulated.baseline = data.frame(x=x,
                                y=y,
                                z=spatial.trend.function(x, y))
delta = 0.01
delta2= delta * delta
```

```{r}
compute_cylinders<-function(circle, observations, tabulated.baseline){
  x0 = as.numeric(circle['x'])
  y0 = as.numeric(circle['y'])
  rho = as.numeric(circle['rho'])

  d = sqrt((tabulated.baseline$x - x0)^2 + (tabulated.baseline$y - y0)^2)
  in_circle = (d < rho) & !is.na(d)
  mu = sum(tabulated.baseline[in_circle,]$z) * delta2
  
  d = sqrt((observations$x - x0)^2 + (observations$y - y0)^2)
  in_circle = (d < rho) & !is.na(d)
  n_cases_in_circle = sum(in_circle)
  
  ci = qpois(c(0.25,0.95) , lambda=mu)
  p.val = ppois(n_cases_in_circle, lambda=mu, lower.tail=FALSE)
  return (c(n_cases_in_circle, mu, ci, p.val))
}
```



```{r}
integrate(function(y) { 
   sapply(y, function(y) {
     integrate(function(x) spatial.trend.function(x,y), 0, 1)$value
   })
 }, 0, 1)

sum(tabulated.baseline$z) * delta2


```

```{r}
mean.baseline = sum(tabulated.baseline$z) * delta2
total.cases =  nrow(observations)
n.cylinders = 4000
rho = sqrt(1 / mean.baseline / pi) * seq(0.5,2.5,length.out = n.cylinders)


random_radia = runif(n.cylinders, 0, rho)
theta = runif(n.cylinders, 0, 2* pi)

idx = sample(1:nrow(observations), n.cylinders, replace=T)
y0 = observations$y[idx] + sin(theta) * random_radia
x0 = observations$x[idx] + cos(theta) * random_radia

idx1 = (y0 > rho) & (y0 < (1-rho))
idx2 = (x0 > rho) & (x0 < (1-rho))

circles = data.frame(x=x0, y=y0, rho=rho, original.x=observations$x[idx],  original.y=observations$y[idx])
circles = circles[idx1 & idx2,]

circles[,c('n_obs', 'mu', 'lower', 'upper', 'p.val')] = t(apply(circles, 1, compute_cylinders,
                                                  observations, tabulated.baseline))

circles$warning = (circles['p.val'] < 0.05) & (circles['n_obs'] > 0)


circles$likelihood = dpois(circles$n_obs, circles$mu)
circles$likelihood2 = dpois(circles$n_obs-1, circles$mu)
circles$likelihood_dt = dtpois(circles$n_obs, circles$mu)
```

Do the same thing using large circles
```{r}
enlarge_circles<-function(circles, c){
  circles$rho = circles$rho * c
  idx1 = (circles$x > circles$rho) & (circles$y < (1-circles$rho))
  idx2 = (circles$x > circles$rho) & (circles$y < (1-circles$rho))
  circles = circles[idx1 & idx2,]
  return(circles)
}

circles_r2 = enlarge_circles(circles, 1.2)
circles_r3 = enlarge_circles(circles, 1.4)
circles_r4 = enlarge_circles(circles, 1.6)
circles_r5 = enlarge_circles(circles, 1.8)

circles_r2[,c('n_obs', 'mu', 'lower', 'upper', 'p.val')] = t(apply(circles_r2, 1, compute_cylinders,
                                                  observations, tabulated.baseline))

circles_r3[,c('n_obs', 'mu', 'lower', 'upper', 'p.val')] = t(apply(circles_r3, 1, compute_cylinders,
                                                  observations, tabulated.baseline))

circles_r4[,c('n_obs', 'mu', 'lower', 'upper', 'p.val')] = t(apply(circles_r4, 1, compute_cylinders,
                                                  observations, tabulated.baseline))

circles_r5[,c('n_obs', 'mu', 'lower', 'upper', 'p.val')] = t(apply(circles_r5, 1, compute_cylinders,
                                                  observations, tabulated.baseline))

circles_r2$likelihood = dpois(circles_r2$n_obs, circles_r2$mu)
circles_r2$likelihood2 = dpois(circles_r2$n_obs-1, circles_r2$mu)

circles_r3$likelihood = dpois(circles_r3$n_obs, circles_r3$mu)
circles_r3$likelihood2 = dpois(circles_r3$n_obs-1, circles_r3$mu)

circles_r4$likelihood = dpois(circles_r4$n_obs, circles_r4$mu)
circles_r4$likelihood2 = dpois(circles_r4$n_obs-1, circles_r4$mu)

circles_r5$likelihood = dpois(circles_r5$n_obs, circles_r5$mu)
circles_r5$likelihood2 = dpois(circles_r5$n_obs-1, circles_r5$mu)


plot(density(circles_r5$likelihood2 - circles_r5$likelihood))
lines(density(circles_r2$likelihood2 - circles_r2$likelihood),col='red')
lines(density(circles_r3$likelihood2 - circles_r3$likelihood),col='green')
lines(density(circles_r4$likelihood2 - circles_r4$likelihood),col='blue')
lines(density(circles$likelihood2 - circles$likelihood),col='orange')
```

```{r}
library(extraDistr)
circles_r5$likelihood = dpois(circles_r5$n_obs, circles_r5$mu)
circles_r5$likelihood_dt = dtpois(circles_r5$n_obs, circles_r5$mu, a=0)
circles$likelihood_dt = dtpois(circles$n_obs, circles$mu, a=0)

plot_likelihood_diff<-function(circles, x='rho', likelihood2='likelihood2', likelihood='likelihood'){
  plot(circles[,x], circles[,likelihood2]/circles[,likelihood]) 
  abline(h=1, col='red')
}
# 
# plot_likelihood_diff(circles)
# plot_likelihood_diff(circles_r2)
# plot_likelihood_diff(circles_r3)
# plot_likelihood_diff(circles_r4)
plot_likelihood_diff(circles_r5, 'rho', "likelihood2", "likelihood_dt")
plot_likelihood_diff(circles_r5,'rho', "likelihood_dt", "likelihood2")
plot_likelihood_diff(circles_r5, 'rho',"likelihood_dt", "likelihood")
plot_likelihood_diff(circles_r5, 'rho',"likelihood", "likelihood_dt")
#plot_likelihood_diff(circles, 'rho', "likelihood_dt", "likelihood")

```


p.val = ppois(n_cases_in_cylinder, lambda=mu, lower.tail=FALSE)

Root mean square displacement
```{r}
RMSD<-function(x,y){
  return( sqrt(mean(  (x-y) ^2  )))
}

for(i in 1:10){
N = NROW(circles)
circles$sim = rpois(N, lambda = circles$mu)
circles$sim_df = rtpois(N, lambda = circles$mu, a=0)
circles$sim2 = rpois(N, lambda = circles$mu) + 1


print(c(RMSD(circles$sim, circles$n_obs), RMSD(circles$sim_df, circles$n_obs), RMSD(circles$sim2, circles$n_obs)))
}
```



```{r}
PP<-function(circles, correction=0){
  return(ppois(circles$n_obs-correction, lambda=circles$mu, lower.tail=FALSE))
}
pp1 = PP(circles)
pp2 = PP(circles, 1)
```



circles not centered around an event point.
```{r}
mean.baseline = sum(tabulated.baseline$z) * delta2
total.cases =  nrow(observations)

n.cylinders = 10000
rho = sqrt(1 / mean.baseline / pi) * seq(0.5,2.5,length.out = n.cylinders)
y0 = runif(n.cylinders)
x0 = runif(n.cylinders)

idx1 = (y0 > rho) & (y0 < (1-rho))
idx2 = (x0 > rho) & (x0 < (1-rho))

circles2 = data.frame(x=x0, y=y0, rho=rho)

circles2 = circles2[idx1 & idx2,]

circles2[,c('n_obs', 'mu', 'lower', 'upper', 'p.val')] = t(apply(circles2, 1, compute_cylinders,
                                                  observations, tabulated.baseline))
circles2$warning = (circles2['p.val'] < 0.05) & (circles2['n_obs'] > 0)
```



```{r}
par(mfrow=c(2,2))

plot(c(circles2$mu, circles$mu), c(circles2$n_obs, circles$n_obs), col='white')
points(circles$mu, circles$n_obs)
lines(0:20, 0:20, col='green')

plot(c(circles2$mu, circles$mu), c(circles2$n_obs, circles$n_obs), col='white')
points(circles$mu, circles$n_obs)
lines(0:20, 0:20 + 1, col='green')

plot(c(circles2$mu, circles$mu), c(circles2$n_obs, circles$n_obs), col='white')
points(circles2$mu, circles2$n_obs)
lines(0:20, 0:20, col='green')

plot(c(circles2$mu, circles$mu), c(circles2$n_obs, circles$n_obs), col='white')
points(circles2$mu, circles2$n_obs)
lines(0:20, 0:20 + 1, col='green')


```


#########



